# Generated by Django 5.1.7 on 2025-04-28 10:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="price",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="available_until",
            field=models.DateField(default=app.models.default_available_until),
        ),
    ]
