# Generated by Django 5.1.7 on 2025-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="location",
        ),
        migrations.AddField(
            model_name="apartment",
            name="city",
            field=models.CharField(default="Oslo", max_length=100),
        ),
        migrations.AddField(
            model_name="apartment",
            name="country",
            field=models.CharField(default="Norway", max_length=100),
        ),
        migrations.AddField(
            model_name="apartment",
            name="shared_bathroom",
            field=models.BooleanField(default=False),
        ),
    ]
