# Generated by Django 5.1.4 on 2025-05-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_apartment_location_apartment_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='shared_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
