# Generated by Django 5.1.7 on 2025-05-29 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_apartment_shared_kitchen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
