# Generated by Django 5.1.7 on 2025-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_rename_timestamp_message_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
