# Generated by Django 5.1.7 on 2025-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="swaprequest",
            name="swap_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
