# Generated by Django 5.1.7 on 2025-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_swaprequest_swap_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="swaprequest",
            old_name="swap_date",
            new_name="swap_end_date",
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="swap_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
