# Generated by Django 5.1.5 on 2025-05-31 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_swap_date_swaprequest_swap_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('inappropriate', 'Inappropriate Behavior'), ('spam', 'Spam or Scam'), ('harassment', 'Harassment'), ('other', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
